[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mawari = "4fdmVM3iqcGLFCvyrtJ1WGhfjdyRMnAxo5h8DpdErRaY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
