[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
mawari = "CqH7CAWwN3PfXgMNLQzGRg277Ki9xE9uoo95L2avcmgQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jay/.config/solana/my-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
